### ISSUE TITLE
e os créditos amigão?

### ISSUE THREAD

**Issue by arthuronze** [esmeraldjs/esmerald.js#3]
o repo é uma cópia do meu [código antigo](https://github.com/drethenrain/erla)

como está esperado na [licença](https://github.com/drethenrain/erla/blob/main/LICENSE), a [primeira condição de uso](https://github.com/drethenrain/erla/blob/main/LICENSE#L9) é manter a licença original do código, como visto, não há no seu repo

peço a compreensão de vocês em relação a isso e dêem o devido crédito à minha equipe

**Comment by justleoo** [comment]
olá, bom dia

eu não sou responsável por isso, mas teremos uma resposta em breve sobre, a maioria do projeto foi feita por [atshushi](https://github.com/atshushi) e [vitogiu1](https://github.com/vitogiu1), se puder esperar para vermos sobre, agradeço

**Comment by atshushi** [comment]
Eu sou um dos desenvolvedores, e vamos refazer todo o projeto. Mas enquanto isso iremos dar os créditos.
